/*
 * SPDX-FileCopyrightText: 2024 SAP Spartacus team <spartacus-team@sap.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { NgModule } from '@angular/core';
import {
  AnonymousConsentsModule,
  AuthModule,
  CostCenterOccModule,
  ExternalRoutesModule,
  ProductModule,
  provideFeatureToggles,
  UserModule,
  UserOccModule,
} from '@spartacus/core';
import {
  AnonymousConsentManagementBannerModule,
  AnonymousConsentsDialogModule,
  BannerCarouselModule,
  BannerModule,
  CategoryNavigationModule,
  CmsParagraphModule,
  ConsentManagementModule,
  FooterNavigationModule,
  HamburgerMenuModule,
  HomePageEventModule,
  LinkModule,
  LoginRouteModule,
  LogoutModule,
  MyAccountV2Module,
  MyCouponsModule,
  MyInterestsModule,
  NavigationEventModule,
  NavigationModule,
  NotificationPreferenceModule,
  PageTitleModule,
  PaymentMethodsModule,
  PDFModule,
  ProductCarouselModule,
  ProductDetailsPageModule,
  ProductFacetNavigationModule,
  ProductImagesModule,
  ProductListingPageModule,
  ProductPageEventModule,
  ProductReferencesModule,
  ScrollToTopModule,
  SearchBoxModule,
  SiteContextSelectorModule,
  SiteThemeSwitcherModule,
  StockNotificationModule,
  VideoModule,
} from '@spartacus/storefront';
import { UserFeatureModule } from './features/user/user-feature.module';
import { AdnocBreadcrumbModule } from '../adnoc-storefrontlib/components/adnoc-navigation/adnoc-breadcrumb/adnoc-breadcrumb.module';
import { CartBaseFeatureModule } from './features/cart/cart-base-feature.module';
import { CartSavedCartFeatureModule } from './features/cart/cart-saved-cart-feature.module';
import { CartQuickOrderFeatureModule } from './features/cart/cart-quick-order-feature.module';
import { CartImportExportFeatureModule } from './features/cart/cart-import-export-feature.module';
import { OrderFeatureModule } from './features/order/order-feature.module';
import { CheckoutFeatureModule } from './features/checkout/checkout-feature.module';
import { PersonalizationFeatureModule } from './features/tracking/personalization-feature.module';
import { PdfinvoicesModuleFeatureModule } from './features/pdf-invoices/pdfinvoices-module-feature.module';
import { RequestedDeliveryDateModuleFeatureModule } from './features/requested-delivery-date/requested-delivery-date-module-feature.module';
import { CustomerTicketingFeatureModule } from './features/customer-ticketing/customer-ticketing-feature.module';
import { OrganizationUserRegistrationFeatureModule } from './features/organization/organization-user-registration-feature.module';
import { OrganizationAdministrationFeatureModule } from './features/organization/organization-administration-feature.module';
import { OrganizationAccountSummaryFeatureModule } from './features/organization/organization-account-summary-feature.module';
import { OrganizationUnitOrderFeatureModule } from './features/organization/organization-unit-order-feature.module';
import { OrganizationOrderApprovalFeatureModule } from './features/organization/organization-order-approval-feature.module';
import { ProductConfiguratorFeatureModule } from './features/product-configurator/product-configurator-feature.module';
import { StoreFinderFeatureModule } from './features/storefinder/store-finder-feature.module';
import { AsmFeatureModule } from './features/asm/asm-feature.module';
import { AsmCustomer360FeatureModule } from './features/asm/asm-customer360-feature.module';
import { SegmentRefsFeatureModule } from './features/segment-refs/segment-refs-feature.module';
import { S4omFeatureModule } from './features/s4om/s4om-feature.module';
import { OppsFeatureModule } from './features/opps/opps-feature.module';
import { DigitalPaymentsFeatureModule } from './features/digital-payments/digital-payments-feature.module';
import { SmartEditFeatureModule } from './features/smartedit/smart-edit-feature.module';
import { EstimatedDeliveryDateFeatureModule } from './features/estimated-delivery-date/estimated-delivery-date-feature.module';
import { QualtricsFeatureModule } from './features/qualtrics/qualtrics-feature.module';
import { ProductFutureStockFeatureModule } from './features/product/product-future-stock-feature.module';
import { ProductImageZoomFeatureModule } from './features/product/product-image-zoom-feature.module';
import { QuoteFeatureModule } from './features/quote/quote-feature.module';
import { AdnocTabParagraphContainerModule } from '../adnoc-storefrontlib/components/content';
import { AdnocProductSummaryModule } from '../adnoc-storefrontlib/product/adnoc-product-summary/adnoc-product-summary.module';
import { AdnocProductIntroModule } from '../adnoc-storefrontlib/product/adnoc-product-intro/adnoc-product-intro.module';
import { AdnocProductListModule } from '../adnoc-storefrontlib/product/adnoc-product-list/adnoc-product-list.module';
import { AdnocProductOccModule } from '../../occ/adapters/product/adnoc-product-occ.module';
import { AdnocStatementOfAccountModule } from '../adnoc-storefrontlib/user/profile/components/adnoc-statement-of-account-component';
import { AdnocPayerOverdueInvoicesModule } from '../adnoc-storefrontlib/user/profile/components/adnoc-payer-overdue-invoices/adnoc-payer-overdue-invoices.module';
import { AdnocOverdueInvoicesPaymentSuccessModule } from '../adnoc-storefrontlib/user/profile/components/adnoc-overdue-invoices-payment-success/adnoc-overdue-invoices-payment-success.module';
import { AdnocUserCreditOrderInfoModule } from '../adnoc-storefrontlib/user/profile/components/adnoc-user-credit-order-info/adnoc-user-credit-order-info.module';
import { AdnocProductTabsModule } from '../adnoc-storefrontlib/product/adnoc-product-tabs';

@NgModule({
  declarations: [],
  imports: [
    AuthModule.forRoot(),
    LogoutModule,
    LoginRouteModule,
    HamburgerMenuModule,
    SiteContextSelectorModule,
    LinkModule,
    BannerModule,
    CmsParagraphModule,
    AdnocTabParagraphContainerModule,
    BannerCarouselModule,
    CategoryNavigationModule,
    NavigationModule,
    FooterNavigationModule,
    AdnocBreadcrumbModule,
    ScrollToTopModule,
    PageTitleModule,
    VideoModule,
    PDFModule,
    SiteThemeSwitcherModule,
    UserModule,
    UserOccModule,
    PaymentMethodsModule,
    NotificationPreferenceModule,
    MyInterestsModule,
    MyAccountV2Module,
    StockNotificationModule,
    ConsentManagementModule,
    MyCouponsModule,
    AnonymousConsentsModule.forRoot(),
    AnonymousConsentsDialogModule,
    AnonymousConsentManagementBannerModule,
    ProductModule.forRoot(),
    AdnocProductOccModule,
    ProductDetailsPageModule,
    ProductListingPageModule,
    AdnocProductListModule,
    SearchBoxModule,
    ProductFacetNavigationModule,
    AdnocProductTabsModule,
    ProductCarouselModule,
    ProductReferencesModule,
    ProductImagesModule,
    AdnocProductSummaryModule,
    AdnocProductIntroModule,
    CostCenterOccModule,
    NavigationEventModule,
    HomePageEventModule,
    ProductPageEventModule,
    ExternalRoutesModule.forRoot(),
    UserFeatureModule,
    CartBaseFeatureModule,
    CartSavedCartFeatureModule,
    CartQuickOrderFeatureModule,
    CartImportExportFeatureModule,
    OrderFeatureModule,
    CheckoutFeatureModule,
    PersonalizationFeatureModule,
    PdfinvoicesModuleFeatureModule,
    RequestedDeliveryDateModuleFeatureModule,
    CustomerTicketingFeatureModule,
    OrganizationUserRegistrationFeatureModule,
    OrganizationAdministrationFeatureModule,
    OrganizationAccountSummaryFeatureModule,
    OrganizationUnitOrderFeatureModule,
    OrganizationOrderApprovalFeatureModule,
    ProductConfiguratorFeatureModule,
    StoreFinderFeatureModule,
    AsmFeatureModule,
    AsmCustomer360FeatureModule,
    SegmentRefsFeatureModule,
    S4omFeatureModule,
    OppsFeatureModule,
    DigitalPaymentsFeatureModule,
    SmartEditFeatureModule,
    EstimatedDeliveryDateFeatureModule,
    QualtricsFeatureModule,
    ProductFutureStockFeatureModule,
    ProductImageZoomFeatureModule,
    QuoteFeatureModule,
    AdnocStatementOfAccountModule,
    AdnocPayerOverdueInvoicesModule,
    AdnocOverdueInvoicesPaymentSuccessModule,
    AdnocUserCreditOrderInfoModule,
  ],
  providers: [
    provideFeatureToggles({
      showDeliveryOptionsTranslation: true,
      formErrorsDescriptiveMessages: true,
      showSearchingCustomerByOrderInASM: true,
      showStyleChangesInASM: false,
      shouldHideAddToCartForUnpurchasableProducts: false,
      useExtractedBillingAddressComponent: false,
      showBillingAddressInDigitalPayments: false,
      searchBoxV2: false,
      trendingSearches: false,
      useProductCarouselBatchApi: true,
      propagateErrorsToServer: true,
      ssrStrictErrorHandlingForHttpAndNgrx: true,
      productConfiguratorDeltaRendering: true,
      a11yUseProperTextColorForFutureStockAccordion: true,
      a11yNavMenuExpandStateReadout: true,
      a11yPreventHorizontalScroll: true,
      a11yPopoverHighContrast: true,
      a11yTabsManualActivation: true,
      a11yCartImportConfirmationMessage: true,
      a11yAnonymousConsentMessageInDialog: true,
      a11yMobileFocusOnFirstNavigationItem: true,
      a11yQuickOrderSearchListKeyboardNavigation: false,
      a11ySearchboxLabel: true,
      a11yStyleExternalLinksAsLinks: true,
      a11ySelectLabelWithContextForSelectedAddrOrPayment: true,
      a11yUseTrapTabInsteadOfTrapInDialogs: true,
      a11yKeyboardAccessibleZoom: true,
      a11yOrganizationLinkableCells: true,
      a11yPreventSRFocusOnHiddenElements: true,
      a11yTruncatedTextStoreFinder: true,
      a11yTruncatedTextUnitLevelOrderHistory: true,
      a11ySemanticPaginationLabel: true,
      a11yPreventCartItemsFormRedundantRecreation: true,
      a11yNotificationPreferenceFieldset: true,
      a11yImproveContrast: true,
      a11yScreenReaderBloatFix: true,
      a11yTabComponent: true,
      a11yCarouselArrowKeysNavigation: true,
      a11yPickupOptionsTabs: true,
      a11yNotificationsOnConsentChange: true,
      a11yDisabledCouponAndQuickOrderActionButtonsInsteadOfRequiredFields: true,
      a11yResetFocusAfterNavigating: true,
      headerLayoutForSmallerViewports: true,
      a11yStoreFinderAlerts: true,
      a11yFormErrorMuteIcon: true,
      a11yImprovedErrorMessage: true,
      a11yStoreFinderLabel: true,
      a11yCxMessageFocus: true,
      occCartNameAndDescriptionInHttpRequestBody: true,
      a11yLinkBtnsToTertiaryBtns: true,
      a11yRepeatedPageTitleFix: true,
      a11yDeliveryModeRadiogroup: true,
      a11yNgSelectOptionsCount: false,
      a11yNgSelectCloseDropdownOnEscape: true,
      a11ySelectImprovementsCustomerTicketingCreateSelectbox: true,
      a11yNgSelectAriaLabelDropdownCustomized: true,
      a11yRepeatedCancelOrderError: true,
      a11yAddedToCartActiveDialog: true,
      a11yNgSelectMobileReadout: true,
      a11yDeliveryMethodFieldset: true,
      a11yShowMoreReviewsBtnFocus: true,
      a11yQuickOrderAriaControls: true,
      a11yRemoveStatusLoadedRole: true,
      a11yDialogsHeading: true,
      a11yDialogTriggerRefocus: true,
      a11yAddToWishlistFocus: true,
      a11ySearchBoxFocusOnEscape: true,
      a11yUpdatingCartNoNarration: true,
      a11yPasswordVisibliltyBtnValueOverflow: true,
      a11yItemCounterFocus: true,
      a11yScrollToReviewByShowReview: true,
      a11yViewHoursButtonIconContrast: true,
      a11yStoreInStockIconContrast: true,
      a11yCheckoutStepsLandmarks: true,
      a11yQTY2Quantity: true,
      a11yImproveButtonsInCardComponent: true,
      a11yMiniCartFocusOnMobile: true,
      a11yApprovalProcessWithNoClearable: true,
      a11yPostRegisterSuccessMessage: true,
      a11yDeleteButton2First: true,
      a11yShowLabelOfSelect: true,
      a11yShowDownArrowOnFocusedSelectMenu: true,
      a11yCroppedFocusRing: true,
      a11yTextSpacingAdjustments: true,
      a11yTableHeaderReadout: true,
      a11ySearchboxAssistiveMessage: true,
      updateConsentGivenInOnChanges: true,
      a11yDifferentiateFocusedAndSelected: true,
      a11yQuickOrderSearchBoxRefocusOnClose: true,
      a11yKeyboardFocusInSearchBox: true,
      a11yAddPaddingToCarouselPanel: true,
      a11yNavigationButtonsAriaFixes: true,
      a11yFocusOnCardAfterSelecting: true,
      a11ySearchableDropdownFirstElementFocus: true,
      a11yHideConsentButtonWhenBannerVisible: true,
      a11yRepeatingButtonsUniqueLabels: true,
      a11yHighContrastBorders: true,
      a11yRegionAssociatedHeaders: true,
      cmsBottomHeaderSlotUsingFlexStyles: true,
      useSiteThemeService: true,
      enableConsecutiveCharactersPasswordRequirement: true,
      enablePasswordsCannotMatchInPasswordUpdateForm: true,
      allPageMetaResolversEnabledInCsr: true,
      a11yPdpGridArrangement: true,
      a11yHamburgerMenuTrapFocus: true,
      useExtendedMediaComponentConfiguration: true,
      showRealTimeStockInPDP: false,
      a11yScrollToTopPositioning: true,
      a11yWideScreenImprovements: true,
      a11yWrapReviewOrderInSection: true,
      a11yOptimizedMenuSpacing: true,
      a11yNgSelectLayering: true,
      a11yNgSelectAriaControls: true,
      enableCarouselCategoryProducts: true,
      enableSecurePasswordValidation: true,
      enableClaimCustomerCouponWithCodeInRequestBody: false,
      enableReadDomainValuesOnDemand: true,
      opfEnablePreventingFromCheckoutWithoutEmail: true,
    }),
  ],
})
export class SpartacusFeaturesModule {}
